version: 1.0.{build}-alpha
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_build:
  - nuget restore Telegram.Bot.Extensions.Filters.sln

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
  
nuget:
  disable_publish_on_pr: true
  
deploy:
  - provider: NuGet
    api_key:
      secure: tsJ7bmzSgZOeIpPL1GcpBkGcz6H4Ymrms4kmr/Q2RBTO3qNDA5A5HIDsjoAsVwLe
    on:
      appveyor_repo_tag: true